### ISSUE TITLE
No need for paths in npm scripts

### ISSUE THREAD

**Issue by lrsjng** [argelius/chai-es6-sample#1]
Good article!

Just for your interest, you don't need the extra paths [here](https://github.com/argelius/chai-es6-sample/blob/master/package.json#L6-L10).

``` json
"scripts": {
    "test": "mocha --compilers js:babel/register",
    "coverage": "istanbul cover _mocha -- --compilers js:babel/register",
    "coverage-es6": "babel-node isparta cover _mocha" 
},
```

**Comment by argelius** [comment]
Thanks!

Glad you liked the article! :)
A bit late but I removed the unnecessary paths.
